[package]
name         = "zx-p2p"
description  = "libp2p: transporte, descubrimiento, gossip, sync headers-first"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
