[package]
name         = "zx-mempool"
description  = "Validación de tx pendientes, orden por fee, constructor de plantilla de bloque"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
